#!/usr/bin/env bash
# simpl-catalogue-local — bring up the full catalogue stack on a local Mac.
#
# Idempotent: re-running skips clone / build / image-build steps if their outputs
# already exist. Use ./stop.sh --full to wipe everything and start fresh.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UPSTREAM_REPO="$REPO_DIR/repos/simpl-fc-service"
UPSTREAM_GIT="https://code.europa.eu/simpl/simpl-open/development/gaia-x-edc/simpl-fc-service.git"
UI_REPO="$REPO_DIR/repos/simpl-catalogue-client"
UI_GIT="https://code.europa.eu/simpl/simpl-open/development/gaia-x-edc/simpl-catalogue-client.git"
QMA_REPO="$REPO_DIR/repos/poc-gaia-edc"
QMA_GIT="https://code.europa.eu/simpl/simpl-open/development/gaia-x-edc/poc-gaia-edc.git"

# Load env overrides if present. Defaults match what start.sh / docker-compose.yml expect.
if [ -f "$REPO_DIR/.env" ]; then
  # shellcheck disable=SC1091
  set -a; . "$REPO_DIR/.env"; set +a
fi

NEO4J_USER="${NEO4J_USER:-neo4j}"
NEO4J_PASSWORD="${NEO4J_PASSWORD:-neo12345}"
FC_SERVICE_PORT="${FC_SERVICE_PORT:-8081}"
NEO4J_HTTP_PORT="${NEO4J_HTTP_PORT:-7474}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"

echo "==> 1/5 Clone upstream simpl-fc-service (if missing)"
mkdir -p "$REPO_DIR/repos"
if [ ! -d "$UPSTREAM_REPO/.git" ]; then
  git clone "$UPSTREAM_GIT" "$UPSTREAM_REPO"
else
  echo "    Already cloned. To update: cd repos/simpl-fc-service && git pull"
fi

echo "==> 2/5 Build fc-service JAR with Maven (if missing)"
# Glob: upstream version is in parent POM <revision> property; we don't pin it here.
JAR_FOUND=$(ls "$UPSTREAM_REPO"/fc-service-server/target/fc-service-server-*.jar 2>/dev/null | head -1 || true)
if [ -z "$JAR_FOUND" ]; then
  echo "    No JAR found; running ./mvnw clean install -DskipTests (5-15 min on first run)..."
  (cd "$UPSTREAM_REPO" && ./mvnw clean install -DskipTests)
else
  echo "    JAR exists: $(basename "$JAR_FOUND"). To rebuild: rm repos/simpl-fc-service/fc-service-server/target/*.jar"
fi

echo "==> 3/5 Build fc-service Docker image (if missing)"
if ! docker image inspect simpl-fc-service:local > /dev/null 2>&1; then
  (cd "$UPSTREAM_REPO" && docker build -t simpl-fc-service:local .)
else
  echo "    Image simpl-fc-service:local exists. To rebuild: docker rmi simpl-fc-service:local"
fi

echo "==> 4a/5 Clone simpl-catalogue-client (if missing) and build its Docker image"
if [ ! -d "$UI_REPO/.git" ]; then
  echo "    Cloning $UI_GIT ..."
  git clone "$UI_GIT" "$UI_REPO"
else
  echo "    Already cloned. To update: cd repos/simpl-catalogue-client && git pull"
fi

# Astro PUBLIC_ env vars are baked into the bundle at build time via dotenvx,
# so we drop a .env into the cloned source dir before the docker build. This
# file is auto-generated; edit ours via .env (gitignored) at repo root if you
# want different URLs/ports.
cat > "$UI_REPO/.env" <<EOF
# Auto-generated by simpl-catalogue-local/start.sh — do NOT edit by hand.
# Empty Keycloak vars disable auth. URLs point at the host's published ports
# of the local stack; the ui container has extra_hosts: localhost:host-gateway
# so localhost inside the container resolves to the host gateway, which
# forwards to fc-service.
PUBLIC_AUTH_KEYCLOAK_SERVER_URL=
PUBLIC_AUTH_KEYCLOAK_REALM=
PUBLIC_AUTH_KEYCLOAK_CLIENT_ID=
PUBLIC_FEDERATED_CATALOGUE_API_URL=http://localhost:${FC_SERVICE_PORT}
PUBLIC_SEARCH_API_URL=http://localhost:${FC_SERVICE_PORT}
PUBLIC_SEARCH_API_VERSION=v1
PUBLIC_QUERY_MAPPER_ADAPTER_API_URL=http://localhost:${QMA_PORT:-8084}
PUBLIC_QUERY_MAPPER_ADAPTER_API_VERSION=v1
PUBLIC_CONTRACT_CONSUMPTION_API_URL=
PUBLIC_CONTRACT_CONSUMPTION_API_VERSION=v1
PUBLIC_AGENT_TYPE=consumer
USE_MOCK_APIS=false
EOF

if ! docker image inspect simpl-catalogue-client:local > /dev/null 2>&1; then
  echo "    Building catalogue UI Docker image (3-5 min on first run)..."
  (cd "$UI_REPO" && docker build -t simpl-catalogue-client:local .)
else
  echo "    Image simpl-catalogue-client:local exists. To rebuild after env-var changes: docker rmi simpl-catalogue-client:local && ./start.sh"
fi

echo "==> 4b/5 Clone poc-gaia-edc (query-mapper-adapter, if missing) and build its Docker image"
if [ ! -d "$QMA_REPO/.git" ]; then
  echo "    Cloning $QMA_GIT ..."
  git clone "$QMA_GIT" "$QMA_REPO"
else
  echo "    Already cloned. To update: cd repos/poc-gaia-edc && git pull"
fi

QMA_JAR=$(ls "$QMA_REPO"/target/adapter-*.jar 2>/dev/null | head -1 || true)
if [ -z "$QMA_JAR" ]; then
  echo "    No JAR found; running ./mvnw clean install -DskipTests..."
  (cd "$QMA_REPO" && PROJECT_RELEASE_VERSION=local ./mvnw clean install -DskipTests)
else
  echo "    JAR exists: $(basename "$QMA_JAR"). To rebuild: rm repos/poc-gaia-edc/target/*.jar"
fi

if ! docker image inspect query-mapper-adapter:local > /dev/null 2>&1; then
  echo "    Building query-mapper-adapter Docker image..."
  (cd "$QMA_REPO" && docker build -t query-mapper-adapter:local .)
else
  echo "    Image query-mapper-adapter:local exists. To rebuild: docker rmi query-mapper-adapter:local"
fi

echo "==> 4c/5 Start stack (postgres + neo4j + fc-service + query-mapper-adapter + ui)"
(cd "$REPO_DIR" && docker compose up -d)

echo "==> 5/5 Initialise n10s graph in Neo4j (workaround for upstream wiring bug)"
echo "    Waiting for Neo4j to accept queries..."
ATTEMPTS=0
until docker exec simpl-cat-neo4j cypher-shell -u "$NEO4J_USER" -p "$NEO4J_PASSWORD" "RETURN 1;" > /dev/null 2>&1; do
  ATTEMPTS=$((ATTEMPTS + 1))
  if [ "$ATTEMPTS" -gt 60 ]; then
    echo "    Neo4j still unreachable after 120s. Check 'docker logs simpl-cat-neo4j'."
    exit 1
  fi
  sleep 2
done
echo "    Neo4j ready."

# Both n10s commands are idempotent. Errors are usually "already exists" — safe to ignore.
docker exec simpl-cat-neo4j cypher-shell -u "$NEO4J_USER" -p "$NEO4J_PASSWORD" \
  "CALL n10s.graphconfig.init({handleVocabUris:'MAP',handleMultival:'ARRAY',multivalPropList:['http://w3id.org/gaia-x/service#claimsGraphUri']});" \
  > /dev/null 2>&1 || echo "    n10s.graphconfig.init already done (idempotent — safe to ignore)"

docker exec simpl-cat-neo4j cypher-shell -u "$NEO4J_USER" -p "$NEO4J_PASSWORD" \
  "CREATE CONSTRAINT n10s_unique_uri IF NOT EXISTS FOR (r:Resource) REQUIRE r.uri IS UNIQUE;" \
  > /dev/null 2>&1 || true

echo ""
echo "==> Stack ready"
echo ""
echo "    Catalogue UI:  http://localhost:${UI_PORT:-4321}"
echo "    fc-service:    http://localhost:${FC_SERVICE_PORT}"
echo "    query-mapper:  http://localhost:${QMA_PORT:-8084}  (catalogue-adapter / poc-gaia-edc)"
echo "    Neo4j Browser: http://localhost:${NEO4J_HTTP_PORT}  (login: ${NEO4J_USER} / ${NEO4J_PASSWORD})"
echo "    Postgres:      localhost:${POSTGRES_PORT}  (user: ${DB_USER:-postgres} / database: fed_cat)"
echo ""
echo "    Try:"
echo "      curl http://localhost:${FC_SERVICE_PORT}/self-descriptions"
echo "      curl http://localhost:${FC_SERVICE_PORT}/schemas"
echo ""
echo "    Logs:"
echo "      docker logs -f simpl-cat-fc-service"
echo ""
echo "    Stop:"
echo "      ./stop.sh           (preserve data + volumes)"
echo "      ./stop.sh --full    (also wipe data — n10s init will re-run on next start)"
